// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarviaBackend.Modules.Platforms.Infrastructure.EF.Contexts;

#nullable disable

namespace StarviaBackend.Modules.Platforms.Infrastructure.Migrations
{
    [DbContext(typeof(PlatformsWriteDbContext))]
    partial class PlatformsWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platforms")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StarviaBackend.Modules.Platforms.Core.Platforms.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<int>("PlatformType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Platforms", "platforms");
                });

            modelBuilder.Entity("StarviaBackend.Modules.Platforms.Core.Platforms.Entities.UserPlatform", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("AccountComment")
                        .HasColumnType("text");

                    b.Property<string>("AccountUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ExternalAccountId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfilePictureLink")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("UserPlatforms", "platforms");
                });

            modelBuilder.Entity("StarviaBackend.Modules.Platforms.Core.Platforms.Entities.UserPlatform", b =>
                {
                    b.HasOne("StarviaBackend.Modules.Platforms.Core.Platforms.Entities.Platform", "Platform")
                        .WithMany("UserPlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("StarviaBackend.Modules.Platforms.Core.Platforms.Entities.Platform", b =>
                {
                    b.Navigation("UserPlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
