
services:


  database:
    image: postgres:17.6
    container_name: PostgresDatabase
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - database_pgdata:/var/lib/postgresql/data


  rustfs:
    image: rustfs/rustfs:latest
    container_name: starvia-rustfs
    restart: unless-stopped

    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: admin

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - rustfs_data:/data


  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq


  redis:
    image: redis:latest
    container_name: Redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data


  mailhog:
    image: mailhog/mailhog:latest
    container_name: MailHog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  database_pgdata: { }
  redisdata: { }
  miniodata: { }
  rabbitmqdata: { }
  rustfs_data: { }
