<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Service</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Google.GenAI" Version="1.6.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="Minio" Version="7.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.0" />
    <PackageReference Include="Stripe.net" Version="51.1.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Repository\Repository.csproj" />
	</ItemGroup>

</Project>
